istoreos: use dedicated overlay partition and support sandbox

diff --git a/package/base-files/files/lib/upgrade/stage2 b/package/base-files/files/lib/upgrade/stage2
--- a/package/base-files/files/lib/upgrade/stage2
+++ b/package/base-files/files/lib/upgrade/stage2
@@ -18,17 +18,19 @@ include /lib/upgrade
 
 supivot() { # <new_root> <old_root>
 	/bin/mount | grep "on $1 type" 2>&- 1>&- || /bin/mount -o bind $1 $1
-	mkdir -p $1$2 $1/proc $1/sys $1/dev $1/tmp $1/overlay && \
-	/bin/mount -o noatime,move /proc $1/proc && \
+	mkdir -p $1$2 $1/proc $1/sys $1/dev $1/tmp $1/overlay $1/ext_overlay && \
+	/bin/mount -o noatime,rbind /proc $1/proc && \
 	pivot_root $1 $1$2 || {
 		/bin/umount -l $1 $1
 		return 1
 	}
 
-	/bin/mount -o noatime,move $2/sys /sys
-	/bin/mount -o noatime,move $2/dev /dev
-	/bin/mount -o noatime,move $2/tmp /tmp
+	/bin/mount -o noatime,move $2/sys /sys || /bin/mount -o noatime,rbind $2/sys /sys
+	/bin/mount -o noatime,move $2/dev /dev || /bin/mount -o noatime,rbind $2/dev /dev
+	/bin/mount -o noatime,move $2/tmp /tmp || /bin/mount -o noatime,bind $2/tmp /tmp
 	/bin/mount -o noatime,move $2/overlay /overlay 2>&-
+	/bin/mount -o noatime,move $2/ext_overlay /ext_overlay 2>&-
+	/bin/umount -l $2/proc $2/sys $2/dev $2/tmp $2/overlay $2/ext_overlay 2>&-
 	return 0
 }
 
@@ -62,6 +64,14 @@ switch_to_ramfs() {
 
 	[ -L "/lib64" ] && ln -s /lib $RAM_ROOT/lib64
 
+	# avoid shared rootfs, which makes `/bin/mount -o noatime,move * *` fail
+	# https://github.com/istoreos/istoreos/issues/1200
+	mount --make-private / 2>&-
+	mount --make-private /tmp 2>&-
+	mount --make-private /mnt 2>&-
+	mount --make-private /overlay 2>&-
+	mount --make-private /ext_overlay 2>&-
+
 	supivot $RAM_ROOT /mnt || {
 		v "Failed to switch over to ramfs. Please reboot."
 		exit 1
@@ -78,11 +88,6 @@ switch_to_ramfs() {
 	[ "$RAMFS_COPY_LVM" ] && {
 		mkdir -p /tmp/lvm/cache
 		$RAMFS_COPY_LVM vgchange -aln --ignorelockingfailure
-	}
-
-	grep /overlay /proc/mounts > /dev/null && {
-		/bin/mount -o noatime,remount,ro /overlay
-		/bin/umount -l /overlay
 	}
 }
 
@@ -132,6 +137,50 @@ kill_remaining() { # [ <signal> [ <loop> ] ]
 	done
 }
 
+istoreos_pre_upgrade() {
+	if [ -n "$UPGRADE_BACKUP" ]; then
+		touch /usr/lib/opkg/.upgrading 2>/dev/null && sync /
+		# reset rom uuid in ext_overlay
+		if [ -e /ext_overlay/etc ]; then
+			[ -f /ext_overlay/upper/usr/lib/opkg/.upgrading ] || {
+				rm -f /ext_overlay/upper/usr/lib/opkg/.upgrading
+				mkdir -p /ext_overlay/upper/usr/lib/opkg
+				touch /ext_overlay/upper/usr/lib/opkg/.upgrading 2>/dev/null
+			}
+			touch /ext_overlay/.upgrading
+			[ -f /ext_overlay/upper/usr/lib/opkg/.upgrading ] && rm -f /ext_overlay/etc/.extroot-uuid
+			sync /ext_overlay
+		fi
+		[ -f /overlay/upper/usr/lib/opkg/.upgrading ] || {
+			rm -f /overlay/upper/usr/lib/opkg/.upgrading
+			mkdir -p /overlay/upper/usr/lib/opkg
+			touch /overlay/upper/usr/lib/opkg/.upgrading 2>/dev/null
+			touch /overlay/.upgrading
+			sync /overlay
+		}
+	fi
+}
+
+istoreos_show_new_firmware_version() {
+	local dist version revision
+	json_load "$(cat /tmp/sysupgrade.meta)" || {
+		return 1
+	}
+	json_select "version"
+	json_get_var dist "dist"
+	json_get_var version "version"
+	json_get_var revision "revision"
+
+	v "Flashing Version: '$dist $version $revision'"
+}
+
+date '+%Y-%m-%d %H:%M:%S' >/overlay/upgrade.log
+export SAVE_LOG=1
+v "Running Version: $(grep DISTRIB_DESCRIPTION= /etc/openwrt_release | cut -d= -f2)"
+if [ -s /tmp/sysupgrade.meta ]; then
+	(istoreos_show_new_firmware_version)
+fi
+
 indicate_upgrade
 
 while read -r a b c; do
@@ -156,19 +205,35 @@ killall -9 ash 2>/dev/null
 
 kill_remaining TERM
 sleep 4
+sync
 kill_remaining KILL 1
 
 sleep 6
 
 echo 3 > /proc/sys/vm/drop_caches
 
+[ -n "$IMAGE" ] && istoreos_pre_upgrade
+
 if [ -n "$IMAGE" ] && type 'platform_pre_upgrade' >/dev/null 2>/dev/null; then
 	platform_pre_upgrade "$IMAGE"
 fi
 
-if [ -n "$(rootfs_type)" ]; then
+ROOTFS_TYPE=$(rootfs_type)
+if [ -n "$ROOTFS_TYPE" -a "$ROOTFS_TYPE" != "tmpfs" -a "$ROOTFS_TYPE" != "rootfs" ]; then
 	v "Switching to ramdisk..."
 	switch_to_ramfs
+fi
+
+grep /ext_overlay /proc/mounts > /dev/null && {
+	/bin/mount -o noatime,remount,ro /ext_overlay
+	/usr/bin/umount -R -d -l /ext_overlay 2>/dev/null || /bin/umount -l /ext_overlay
+}
+
+if [ -z "$UPGRADE_BACKUP" ]; then
+grep /overlay /proc/mounts > /dev/null && {
+	/bin/mount -o noatime,remount,ro /overlay
+	/usr/bin/umount -R -d -l /overlay 2>/dev/null || /bin/umount -l /overlay
+}
 fi
 
 # Exec new shell from ramfs
